/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                                                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <bits/stdc++.h>
using namespace std;

int main()
{
    long sum = 0, a = 1, b = 1, c = a + b;
    while(b < 4000000)
    {
        sum += c;
        a = b + c;
        b = a + c;
        c = a + b;        
    }

    cout<<sum<<endl;
}