/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:
                        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <bits/stdc++.h>
using namespace std;

int main()
{
    vector<int> divisors;
    long triangleNum = 0;
    int n = 1;

    while (divisors.size() <= 501)
    {
        divisors.clear();
        triangleNum += n;
        for (int i=1;i<=sqrt(triangleNum);i++)
        {
            if (triangleNum%i == 0) {
                if (triangleNum/i == i) divisors.push_back(i);
                else {
                    divisors.push_back(i);
                    divisors.push_back(triangleNum/i);
                }
            }   
        }
        if (divisors.size() > 500)
            cout<<triangleNum<<endl;
        
        n++;
    }
}